# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: MEDIGENT
title-normal: Assisting Healthcare
email: contact@medigent.com
description: Fundacja MEDIGENT wspiera zastosowanie nowych technologii w medycynie.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://medigent.github.io" # the base hostname & protocol for your site
author: Wojciech Francuzik
street_address: ul. Grunwaldzka 66/2
city: Poznań
zip_code: 60-311
country: Poland
phone: +48 508 193 408

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: #https://gitlab.com/u/andrewbanchich
googleplus_url: #https://plus.google.com/u/0/+AndrewBanchich
instagram_url: #https://instagram.com
linkedin_url: #https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: #https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: wolass
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
